apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: config-server
  name: config-server
  namespace: test-cluster-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  strategy: {}
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - image: 885801475464.dkr.ecr.eu-west-3.amazonaws.com/ecr-petclinic:spring-petclinic-config-server
        name: config-server
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 1000m
            memory: 512M
          limits:
            memory: 512M
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: kubernetes
      #  - name: MANAGEMENT_METRICS_EXPORT_WAVEFRONT_URI
      #    value: proxy://wavefront-proxy.spring-petclinic.svc.cluster.local:2878
        ports:
        - containerPort: 8888
      restartPolicy: Always
status: {}