apiVersion: v1
kind: Service
metadata:
  labels:
    app: config-server
  name: config-server
  namespace: test-cluster-petclinic
spec:
  ports:
  - name: "http"
    port: 8888
    targetPort: 8888
  selector:
    app: config-server